### ISSUE TITLE
sensitivity analysis report

### ISSUE THREAD

**Issue by fredericosilva** [larsbeck/Optimization.Solver.GLPKSolver#2]
Hello,

I would like to add support to sensitivity analysis report (glp_print_ranges). Would you be interested in a future PR?

Btw: can you update this repo with the latest v0.3.19 source?

Have a great day.

**Comment by larsbeck** [comment]
Hi Frederico,

I am sorry. I didn't see your  message until now. You are more than welcome to send me a pull request, yes.

Best,

Lars

**Comment by fredericosilva** [comment]
Hello,

I ended up going with a different solver due licensing constraints.

Going to close this issue.

Thank you.
